[package]
name = "metrology_insight"
version = "0.0.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ndarray = "0.16.1"
num-complex = "0.4.6"
rand = "0.8.5"
